#Generated by Edalize
ifndef MODEL_TECH
$(error Environment variable MODEL_TECH was not found. It should be set to <modelsim install path>/bin)
endif

CC ?= gcc
CFLAGS   := -fPIC -fno-stack-protector -g -std=c99
CXXFLAGS := -fPIC -fno-stack-protector -g

LD ?= ld
LDFLAGS := -shared -E

#Try to determine if ModelSim is 32- or 64-bit.
#To manually override, set the environment MTI_VCO_MODE to 32 or 64
ifeq ($(findstring 64, $(shell $(MODEL_TECH)/../vco)),)
CFLAGS   += -m32
CXXFLAGS += -m32
LDFLAGS  += -melf_i386
endif

RM ?= rm
INCS := -I$(MODEL_TECH)/../include

VSIM ?= $(MODEL_TECH)/vsim

TOPLEVEL      := ucsbece154a_top_tb
VPI_MODULES   :=
PARAMETERS    ?=
PLUSARGS      ?=
VSIM_OPTIONS  ?= -voptargs=+acc=lprn
EXTRA_OPTIONS ?= $(VSIM_OPTIONS) $(addprefix -g,$(PARAMETERS)) $(addprefix +,$(PLUSARGS))
RTL           := text.dat ucsbece154a_alu.v ucsbece154a_controller.v ucsbece154a_datapath.v ucsbece154a_mem.v ucsbece154a_riscv.v ucsbece154a_rf.v ucsbece154a_top.v ucsbece154a_top_tb.v ucsbece154a_defines.vh

all: clean run $(VPI_MODULES) $(RTL)

run: work $(VPI_MODULES) $(RTL)
	$(VSIM) -do "run -all; quit -code [expr [coverage attribute -name TESTSTATUS -concise] >= 2 ? [coverage attribute -name TESTSTATUS -concise] : 0]; exit" -c $(addprefix -pli ,$(VPI_MODULES)) $(EXTRA_OPTIONS) $(TOPLEVEL)

run-gui: work $(VPI_MODULES) $(RTL)
	$(VSIM) -gui $(addprefix -pli ,$(VPI_MODULES)) $(EXTRA_OPTIONS) $(TOPLEVEL)

work: $(RTL)
	$(VSIM) -c -do "do edalize_main.tcl; exit"

clean:
	rm -rf work transcript dump.fst vsim.wlf

# SPIM
%_text.dat %_data.dat: %.s
	@cd $(shell dirname $*) && \
	mkdir -p .dump_$(shell basename $*) && \
	cd .dump_$(shell basename $*) && \
	spim -dump -delayed_branches -notrap -file ../$(shell basename $<) && \
	cut -c16-23 text.asm > text.dat && \
	sed -i '1,2d' text.dat && \
	mv text.dat ../$(shell basename $*_text.dat) && \
	cp data.asm data.dat && \
	sed -i 's/\t/       /g' data.dat && \
	cut -c 35- data.dat > data2.dat && \
	sed -i '1d' data2.dat  && \
	sed -i 's/0x//g' data2.dat  && \
	mv data2.dat ../$(shell basename $*_data.dat) && \
	cd .. && \
	rm -rf .dump_$(shell basename $*) && \
	echo "Created $*_text.dat and $*_data.dat"
